### ISSUE TITLE
Transparent button's icon is not visible in the demo app

### ISSUE THREAD

**Issue by moroshko** [seek-oss/seek-style-guide#147]
White icon color on a white background 😄 

Have you considered to define button icon's color in `Button.less` for consistency?

<img width="814" alt="screenshot 2017-03-03 21 27 10" src="https://cloud.githubusercontent.com/assets/259753/23576369/3aa2314c-0058-11e7-9ee0-72331a351e9d.png">

**Comment by michaeltaranto** [comment]
Hey Mish! The problem looks to be the [svg fill being set to white](https://github.com/seek-oss/seek-style-guide/blob/master/app/components/Buttons/Buttons.less#L41). Icons use `fill: currentColor` by default, so if we don't override it the icon will follow the colour of the text.

**Comment by markdalgleish** [comment]
Looks like this issue has already been fixed 👍
