### ISSUE TITLE
Router is not working on IE

### ISSUE THREAD

**Issue by LeviSeek** [seek-oss/seek-style-guide#164]
React-Router is not fully supported on IE, well, this is another example.

so basically, on IE, each component's demo page is down.

![image](https://cloud.githubusercontent.com/assets/16127935/24133917/cb643680-0e54-11e7-9a46-8972eb590d45.png)

**Comment by markdalgleish** [comment]
The URL in this example is incorrect, it should be http://seek-oss.github.io/seek-style-guide/footer/. How did you end up at this URL?

**Comment by markdalgleish** [comment]
@LeviSeek just cleaning up old PRs and issues—is this still a problem?

**Comment by markdalgleish** [comment]
Closing this just to clean things up. @LeviSeek, please reopen if this is still an issue.
