### ISSUE TITLE
Autosuggest styling broken

### ISSUE THREAD

**Issue by LeviSeek** [seek-oss/seek-style-guide#258]
if there are 2 text fields(in this case, job title/company name) with autosuggest, the styling for the 1st autosuggest list will be broken.

![image](https://user-images.githubusercontent.com/16127935/28511785-1255fba6-7092-11e7-880c-0e53e5ba5e1c.png)

**Comment by georgespyropoulos** [comment]
Looks like the issue is that the z-index on the `.suggestionsContainer` class was removed in this PR https://github.com/seek-oss/seek-style-guide/pull/241/files

**Comment by kosanna** [comment]
Looking

**Comment by kosanna** [comment]
Hm...@georgespyropoulos it should not be an issue as it's been transferred to a higher level container

**Comment by kosanna** [comment]
Will do a fix in a sec

**Comment by markdalgleish** [comment]
Looks like this is fixed, so closing the issue.
