### ISSUE TITLE
Autosuggest bug for multiple fields on the page

### ISSUE THREAD

**Issue by CaseyLeask** [seek-oss/seek-style-guide#299]
Pull Request #298

NOTE: This template is also available at https://github.com/seek-oss/seek-style-guide/blob/master/.github/ISSUE_TEMPLATE.md if you'd like to refer to it later.

RFC TEMPLATE
============

NOTE: For complete examples, have a look at Yarn's list of accepted RFCs - https://github.com/yarnpkg/rfcs/tree/master/accepted

Issue title:

RFC: {{ Name of proposal }}

Issue body:

# Summary
When multiple Autosuggest exist on a page, clicking on the label always puts focus on the input of the first Component on the page.

# Motivation

https://www.seek.com.au/companies/
Implementing the 'search for a company' functionality.

# Detailed design

When clicking the label, it should focus on the accompanying input field of that Component.

# How We Teach This

?

# Drawbacks

Not sure..

# Alternatives

We'd have to manually work around this.

# Unresolved questions

Full disclosure, we're first time contributors to the Seek Style Guide and we're not completely sure on how to address this.

**Comment by adenj** [comment]
[Preview](http://seek-style-guide--4e69a07750c6efeb1b1c9cf00aff6660cddc6c30.surge.sh/autosuggest)

**Comment by kosanna** [comment]
Can't reproduce the issue. I've corrected the implementation example in the demo in branch `autosuggest-duplication-bug`. Please have a look
