### ISSUE TITLE
RFC: Allow Header to accept custom logo components

### ISSUE THREAD

**Issue by markdalgleish** [seek-oss/seek-style-guide#310]
# Summary

Add support for a custom `logoComponent` prop to the `<Header />` component so custom logo overrides can be provided by consumers.

# Motivation

SEEK has a long history of changing the logo in the header, but this has essentially fallen away as we've moved towards a microservice architecture. Now that we have a living style guide, we have the opportunity to bring this tradition back, albeit with a different technical implementation.

# Detailed design

At least as a first step, I'm proposing that we add a `logoComponent` prop that accepts a React component to render instead of the default `Logo` component.

For example:

```js
import { Header } from 'seek-style-guide/react';

const MyCustomLogo = () => { ... };

<Header {...} logoComponent={MyCustomLogo} />
```

*While we have no immediate plans to do this just yet,* this API is designed to be future-proofed enough to handle logos being included in the style guide in a way that also allows for us to keep our bundle sizes to a minimum. For example:

```js
// NOTE: This is only a concept, not part of this proposal:
import { Header, Logo_NYE } from 'seek-style-guide/react';

<Header {...} logoComponent={Logo_NYE} />
```

# How We Teach This

Since we're already using the `<Logo />` component internally, we can instruct style guide consumers to simply duplicate this and apply the necessary alterations, making it a relatively painless process.

# Drawbacks

This puts the responsibility of managing logo variations onto individual teams, rather than centralising the work. This is a conscious tradeoff, but certainly one to be aware of.

# Alternatives

It was first floated that we could allow you to choose the logo variant via a string/boolean based prop, but this would have a negative effect on bundle size since you would be forced to bundle every logo variation, regardless of whether it actually gets used or not. This option seems like a bit of a non-starter.

We've also talked about potentially including the logo variations in the style guide itself. This is definitely an option, but I'm not sure it makes sense in the long run. Most (if not all) logo variations are quite ephemeral, only being used once. This would lead to constant version churn as we cycle through different logos and remove old ones. Centralising and co-ordinating logo changes definitely makes sense, but I think we should probably have separate infrastructure to achieve this.

Finally, if we agree on the proposed approach, there's still obviously a bit of room to adjust the API. The only other suggestion I'd make is moving towards a `renderLogo` API, which is obviously very similar when dealing with functional components:

```js
import { Header } from 'seek-style-guide/react';

const renderLogo = () => { ... };

<Header {...} renderLogo={renderLogo} />
```

# Unresolved questions

To address some of the concerns with the alternative approach mentioned above, is it okay if we only change the logo in the core job search product (home page, search results and job details)? This would eliminate the need to co-ordinate logo changes cross-team, making this work even simpler, but of course this isn't really a technical decision for us to make without further guidance.

**Comment by markdalgleish** [comment]
Just added the following to the "detailed design" section, to show how this API could be used in the future if we decide to ship logo variants within the style guide itself:

---

While we have no immediate plans to do this just yet, this API is designed to be future-proofed enough to handle logos being included in the style guide in the future, in a way that also allows for us to keep our bundle sizes to a minimum, for example:

```js
import { Header, Logo_NYE } from 'seek-style-guide/react';

<Header {...} logoComponent={Logo_NYE} />
```

**Comment by tamoore** [comment]
That's pretty comprehensive. My only question was the distinction you make between functional components and seemingly composite components. 

I didn't quite understand what the point you were making there. They seem to be ostensibly the same, thoughts?

**Comment by markdalgleish** [comment]
They're basically the same, it's really just an API decision about whether we accept a function or a component.

**Comment by tamoore** [comment]
Definitely, think this is a great idea and look forward to using it on future logo variants. 👍 

On semantics, I'm leaning towards `logoRenderer` in this case. The main justification is two fold:

1. We seem to use `component` prop names when it's a use this, instead of that default. (You could potentially argue this is similar with `logoComponent`, but it feels a little bit removed from that convention.)
2. We're really asking the Header component to render for us an alternate logo temporarily.

Not saying we should use `logoRenderer` was just fielding it for further thought. I took the name from linkRenderer, so it may be a flawed idea. 😉

**Comment by markdalgleish** [comment]
Thinking about this more, I think the `logoComponent` API makes more sense if we ever want to start shipping alternate logos with the style guide, since importing a component is much more common than importing a "renderer".

**Comment by markdalgleish** [comment]
Any further thoughts on this?

**Comment by tamoore** [comment]
I'm happy with this if no one else has any comments.

**Comment by markdalgleish** [comment]
Marking this as approved, PR incoming 🚀
