### ISSUE TITLE
Typo in design principles on website

### ISSUE THREAD

**Issue by lol-russo** [seek-oss/seek-style-guide#313]
'Accessibile' should read 'Accessible'. Super nit picky, but I noticed it so thought I'd let you know 👍

While I'm here - thank you for open sourcing this for others to learn from.

![image](https://user-images.githubusercontent.com/19835679/30273326-e112af0a-973b-11e7-96f0-c1b11d2d754c.png)

**Comment by markdalgleish** [comment]
Thanks so much for taking the time to raise this issue!

Really glad to hear you're getting value from our work in this space—it definitely helps keep us even more motivated 😄
