### ISSUE TITLE
RFC: Add '<ButtonGroup>' component, introduce '<CardGroup>' to replace '<Card group>'

### ISSUE THREAD

**Issue by dborysiewicz** [seek-oss/seek-style-guide#321]
# Summary

There is a need for consistent (& responsive) buttons that are being used with forms.

# Motivation

The initial motivation was to make a form submit button more predominant on mobile by going full-width. However, after discussing this, we've decided it might be a good idea to make this a more general pattern for groups of `Button` components in the context of forms.

Example of implementation:
<img width="1678" alt="screen shot 2017-09-14 at 10 16 25 am" src="https://user-images.githubusercontent.com/7741507/30406590-0f506f3c-9936-11e7-937b-1f9826cced3e.png">

# Detailed design

This will be implemented as a separate `ButtonGroup` component

```js
<ButtonGroup>
  <Button {...} />
  <Button {...} />
</ButtonGroup>
```

`<Button group>` will be a div wrapper that will have `display: flex;` set but also set extra/override css on all nested buttons. This will also include targeting certain button colors with different css overrides.

We currently have a `<Card group>` component, but we're proposing that we also migrate this to a separate `<CardGroup>` component, even if it's just a surface level change for now, rendering a `<Card group>` internally.

# How We Teach This

This should be fairly straightforward since it follows established patterns, i.e. `<Card group>`, soon the be renamed as `<CardGroup>`.

Since it's a new component, we'll add a new `ButtonGroup` page to the demo site.

# Drawbacks

It's not a silver bullet for all implementations of button but should work for most cases with forms.
As usual, it does adds extra complication to the API.

# Alternatives

We could provide a prop (`flexible`?) directly to button without wrapping them in a group, but we'd still need to nest them within a container with `display: flex`. To better support this, we've talked about making a generic `Flex` component, but felt like this would be branching off into a very different pattern to what we current have.

**Comment by mengtzu** [comment]
Sounds reasonable, go ahead.

**Comment by markdalgleish** [comment]
👍

**Comment by markdalgleish** [comment]
Just updated this issue based on the new `<ButtonGroup>` API (instead of `<Button group>`) and noted that we're also aiming to change the `<Card group>` API to `<CardGroup>`.

**Comment by markdalgleish** [comment]
Done 👍
