### ISSUE TITLE
RFC: Textarea description

### ISSUE THREAD

**Issue by mattsjones** [seek-oss/seek-style-guide#325]
# Summary

Add an optional description prop to `Textarea`

# Motivation

This will add the ability to give more context to a `Textarea`, in cases where we want to prompt the user to give specific styles of input or give them ideas on what to write. Currently, we can only add information below the input which is not ideal for mobile and accessibility reasons. 

# Detailed design

Simply add an extra optional string prop called `description` to `Textarea` and render it between the label and the input. This would supercede using the `message` prop for help text and reserve the message for more asynchronous information that may be displayed. 

Other possible prop names: 
- `prompt`
- `help`
- `explanation`

eg.
![image](https://user-images.githubusercontent.com/8802980/30575232-b7580d06-9d42-11e7-9a88-190f23f15989.png)

# How We Teach This

Add prop to the `Textarea` demo page. 

# Drawbacks

The new prop may be confusing when compared with the existing `message` prop. 

This will also introduce extra space between the label and the input in cases where it is used. This could become a problem on mobile devices, especially if too much text is entered. 

# Alternatives

Alternatively, we could continue adding help text below the field.

**Comment by georgespyropoulos** [comment]
Sounds good to me 👏

**Comment by markdalgleish** [comment]
Sounds good to me too 👏 

Marking this as approved.
