### ISSUE TITLE
RFC: Alert styles

### ISSUE THREAD

**Issue by georgespyropoulos** [seek-oss/seek-style-guide#330]
# Summary

Alert styles are a way to highlight certain pieces of copy to give them the correct visual weight and tone to communicate a message to the user.

Big thanks to @stephaniemoss for putting this together!  I am merely the messenger here

# Motivation

Currently our styling for these types of alerts is inconsistent, so there is no pattern to deal with them. This means they get implemented in different ways across streams and products which can confuse the user.

Having a consistent set of patterns for dealing with alerts helps with overall communication, consistency and gives everyone the tools to make sure their copy is seen and understood in the right contexts.

# Detailed design

The alerts are a set of visual patterns that have different types and a hierarchy that can be applied to a number of different implementations.

### Positive

This alert uses green and ticks. It is used for positive and success alerts to let the user know that something has succeeded.

![image](https://user-images.githubusercontent.com/1896277/30675283-f8f29e44-9ec2-11e7-9660-beeda8aa68ba.png)

### Info

This alert uses purple and an i within a circle (info icon). It is used for important information that a user should definitely read.

![image](https://user-images.githubusercontent.com/1896277/30675302-0b7deb90-9ec3-11e7-8d81-2cf761681005.png)

### Critical

This alert uses pink and an exclamation mark in a triangle (error icon). It is used for errors to let a user know that something has gone wrong and they can’t continue.

![image](https://user-images.githubusercontent.com/1896277/30675324-25e9e01a-9ec3-11e7-8161-b5f59b184600.png)

### Help

This alert uses grey and a question mark in a circle (help icon). It is used for helpful but not critical information, usually accessed voluntarily by the user in case they need further instructions or help.

![image](https://user-images.githubusercontent.com/1896277/30675345-41816726-9ec3-11e7-94fb-d576f86d41d2.png)

### Primary

Used when you want the alert to be loud and draw attention. Dark background, light text, light icons.

![image](https://user-images.githubusercontent.com/1896277/30675473-2750c562-9ec4-11e7-8607-64d9642e6383.png)

### Secondary

Used when you want the alert to be on a normal volume level. Light background, dark text, dark icons, underline.

![image](https://user-images.githubusercontent.com/1896277/30675470-24692150-9ec4-11e7-8144-bb9fb439dd59.png)

### Tertiary

Used when the alert should be integrated into the design and not confused with another type of element like a button. Dark icon and text but no background tint or underline.

![image](https://user-images.githubusercontent.com/1896277/30675469-2238cc14-9ec4-11e7-9c72-177357a418bf.png)

## Generic anatomy

![image](https://user-images.githubusercontent.com/1896277/30675494-3b97437a-9ec4-11e7-9a3c-064f311b6b7f.png)

## Colour specifications 

![image](https://user-images.githubusercontent.com/1896277/30675502-4deb43c8-9ec4-11e7-9cb0-8387b119ee0c.png)
![image](https://user-images.githubusercontent.com/1896277/30675507-52a171e4-9ec4-11e7-9187-3ac61fbd8157.png)

## Example alert being used in production

![image](https://user-images.githubusercontent.com/1896277/30675520-5c7e5dd0-9ec4-11e7-98ab-3418fde40a5d.png)

## Code sample

```
<Alert
  type={postitive|info|ciritical|help}
  level={primary|secondary|tertiary}
  message="I am the text that is displayed in the alert"
  position={inline|pullOut|standalone|card}
/>
```

## More details

All images and design details are available here

[Alert styles.zip](https://github.com/seek-oss/seek-style-guide/files/1319741/Alert.styles.zip)

# How We Teach This

Since this is a new feature, there won't be any need to communicate any breaking changes to styleguide consumers.  Alert styles will have their own demo page will which allow designers and developers to view all variations and options that can be applied to alerts.

# Drawbacks

Can't see any reason why we shouldn't have alert styles...

# Alternatives

The current designs are comprehensive and have been through multiple iterations.  The zip file under 'Example uses' shows how the alert styles could be used in across seek's products

The impact of not doing this is that alert styles are not currently uniform, even for teams that use the styleguide heavily.  This RFC is attempting to make alert styling uniform across seek

# Unresolved questions

Should we build all alert options initially or start with an MVP and add features incrementally

**Comment by markdalgleish** [comment]
Could you update the detailed design with some code samples?
