### ISSUE TITLE
move from react-autowhatever to @xavescor/react-autowhatever

### ISSUE THREAD

**Issue by XaveScor** [seek-oss/seek-style-guide#644]
# Motivation
Author of [react/autowhatever](https://github.com/moroshko/react-autowhatever) abadon this library. I fork it to [@xavescor/react-autowhatever](https://github.com/XaveScor/react-autowhatever). My fork has less size, primitive typings, full backward compatibility with react-autowhatever@10.2.0.

I propose you to switch to my fork in your project.

**Comment by markdalgleish** [comment]
This project is actually deprecated in favour of [Braid](https://github.com/seek-oss/braid-design-system) where we've implemented a new autosuggest that doesn't depend on this package.
